[package]
name = "predator_prey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.5"
cairo-rs = { verison = "0.15.12" , features = ["png"] }
rand = "0.8.5"
